version: "3.9"

services:
  redis:
    image: redis:7.2-alpine
    container_name: newsfeeds-redis
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: newsfeeds-celery-worker
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/1
    volumes:
      - ./src:/app
    command: celery -A newsfeeds_demo.celery_app worker --loglevel=info --concurrency=5
